### ISSUE TITLE
Backup script on APP server to be execute by user with 2FA

### ISSUE THREAD

**Issue by SPlanzer** [linz/github-backup-scripts#1]
Currently the back up script running on the APP server is using the linz admin user. Change this to use a 2FA user.

**Comment by SPlanzer** [comment]
related to [#13](https://github.com/linz/ds-dev-team/issues/13)

**Comment by SPlanzer** [comment]
Done - using my own generated API key. No need for SSH

**Comment by imincik** [comment]
Thanks @SPlanzer
